services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    mem_limit: 1g  # Limit the container memory to 1GB

